### ISSUE TITLE
Notice: Object of class Drupal\Core\Render\Markup could not be converted to int

### ISSUE THREAD

**Issue by gauravmahlawat** [contrib-tracker/backend#270]

**Comment by hussainweb** [comment]
Notices don't typically appear on Sentry. Can you post the stack trace from the error?

**Comment by gauravmahlawat** [comment]
Sure here it is @hussainweb 
Notice: Object of class Drupal\Core\Render\Markup could not be converted to int in __TwigTemplate_728c70901a06a65d2eae005fa9ee9b9f->doDisplay() (line 85 of /var/www/html/web/sites/default/files/php/twig/65321420a29e3_views-view-fields--patche_pO16hZM4E201VoK0QTbaGB8Kz/kIyxHQJJSh58YwJBM4r3fMiL7_x7G7XY6hWx7hH73QU.php)
#0 /var/www/html/web/core/includes/bootstrap.inc(164): _drupal_error_handler_real(8, 'Object of class...', '/var/www/html/w...', 85)
#1 /var/www/html/web/sites/default/files/php/twig/65321420a29e3_views-view-fields--patche_pO16hZM4E201VoK0QTbaGB8Kz/kIyxHQJJSh58YwJBM4r3fMiL7_x7G7XY6hWx7hH73QU.php(85): _drupal_error_handler(8, 'Object of class...', '/var/www/html/w...', 85)
#2 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_728c70901a06a65d2eae005fa9ee9b9f->doDisplay(Array, Array)
#3 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#4 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#5 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#6 /var/www/html/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#7 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/custom/c...', Array)
#8 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('views_view_fiel...', Array)
#9 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#10 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#11 /var/www/html/web/sites/default/files/php/twig/65321420a29e3_views-view-unformatted.ht_31-OjKUPq7QFEjn0RanPy6nf7/Hiaj_Vk-Hp8PbWuux3oHu_hY_ZhpKsFJS3sVooVrdOQ.php(63): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#12 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_00fd383bf624b632d86ecde44ea50153->doDisplay(Array, Array)
#13 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#15 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#16 /var/www/html/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#17 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/contrib/...', Array)
#18 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('views_view_unfo...', Array)
#19 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(458): Drupal\Core\Render\Renderer->doRender(Array)
#20 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#21 /var/www/html/web/core/lib/Drupal/Core/Template/TwigExtension.php(474): Drupal\Core\Render\Renderer->render(Array)
#22 /var/www/html/web/sites/default/files/php/twig/65321420a29e3_views-view--patches_on_is_AMXRWN1QBdnjHZk5u-D3j3Wf7/SIsw3u_z0ZXTKMlAj0TZeKChXmw56f7U2SkfbKTwxZA.php(90): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#23 /var/www/html/vendor/twig/twig/src/Template.php(394): __TwigTemplate_3508f1df28d5ea41af6cd07640e49680->doDisplay(Array, Array)
#24 /var/www/html/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /var/www/html/vendor/twig/twig/src/Template.php(379): Twig\Template->display(Array)
#26 /var/www/html/vendor/twig/twig/src/TemplateWrapper.php(40): Twig\Template->render(Array, Array)
#27 /var/www/html/web/core/themes/engines/twig/twig.engine(53): Twig\TemplateWrapper->render(Array)
#28 /var/www/html/web/core/lib/Drupal/Core/Theme/ThemeManager.php(372): twig_render_template('themes/custom/c...', Array)
#29 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(445): Drupal\Core\Theme\ThemeManager->render('views_view__pat...', Array)
#30 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(458): Drupal\Core\Render\Renderer->doRender(Array)
#31 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(204): Drupal\Core\Render\Renderer->doRender(Array, false)
#32 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(238): Drupal\Core\Render\Renderer->render(Array, false)
#33 /var/www/html/web/core/lib/Drupal/Core/Render/Renderer.php(592): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#34 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(231): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#35 /var/www/html/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(128): Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#36 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#37 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#38 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#39 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(187): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object(Symfony\Component\HttpKernel\Event\ViewEvent), 'kernel.view')
#40 /var/www/html/vendor/symfony/http-kernel/HttpKernel.php(76): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#41 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#42 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#43 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#44 /var/www/html/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#45 /var/www/html/vendor/asm89/stack-cors/src/Cors.php(53): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#46 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Asm89\Stack\Cors->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#47 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#48 /var/www/html/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#49 /var/www/html/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#50 /var/www/html/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#51 {main}

**Comment by rishabaxelerant** [comment]
Issue Handled in #351 
PR #354
